name: Deploy

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: install hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.109.0'

    - name: install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: install python packages
      run: |
        pip3 install requests
        pip3 install pynacl

    - name: update games list
      env:
        NPSSO: ${{ secrets.NPSSO }}
        PSN_ACCESS_TOKEN: ${{ secrets.PSN_ACCESS_TOKEN }}
        PSN_REFRESH_TOKEN: ${{ secrets.PSN_REFRESH_TOKEN }}
        CI_TOKEN: ${{ secrets.CI_TOKEN }}
      run: |
        output=$(python3 .github/scripts/psn.py)
        if [ $? -eq 0 ]; then
          echo "$output" > content/games/index.md
        fi

    - name: build web
      run: |
        hugo -d public --minify

    - name: upload oss
      run: |
        wget http://gosspublic.alicdn.com/ossutil/1.7.8/ossutil64
        chmod 755 ./ossutil64
        ./ossutil64 config -e https://oss-accelerate.aliyuncs.com -i ${{ secrets.ALI_ACCESSKEY_ID }} -k ${{ secrets.ALI_ACCESSKEY_SECRET }} -L CH
        ./ossutil64 cp -r public/ oss://codming-com-blog/ -u

    - name: flush cdn
      run: |
        wget https://aliyuncli.alicdn.com/aliyun-cli-linux-3.0.64-amd64.tgz
        tar -zxvf aliyun-cli-linux-3.0.64-amd64.tgz
        cp aliyun /usr/local/bin/
        aliyun configure set --profile default --mode AK --region cn-hangzhou --access-key-id ${{ secrets.ALI_ACCESSKEY_ID }} --access-key-secret ${{ secrets.ALI_ACCESSKEY_SECRET }}
        aliyun cdn RefreshObjectCaches --region cn-hangzhou --ObjectType Regex --ObjectPath 'https://codming.com/([0-9a-z^/]|.)/'
        aliyun cdn RefreshObjectCaches --region cn-hangzhou --ObjectType File --ObjectPath 'https://codming.com/'
        aliyun cdn RefreshObjectCaches --region cn-hangzhou --ObjectType File --ObjectPath 'https://codming.com/sitemap.xml'
        aliyun cdn RefreshObjectCaches --region cn-hangzhou --ObjectType File --ObjectPath 'https://codming.com/index.xml'
        modified_files=$(git diff --name-only HEAD)
        for file in $modified_files; do
          if [[ $file == content/images/* ]]; then
            url="https://codming.com/${file#content/}"
            echo $url
            aliyun cdn RefreshObjectCaches --region cn-hangzhou --ObjectType File --ObjectPath $url
          fi
        done
        aliyun cdn PushObjectCache --region cn-hangzhou --ObjectPath 'https://codming.com/'
